import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header1 } from "@/components/header";
import { Hero4 } from "@/components/hero";
import { Testimonials1 } from "@/components/testimonials";
import { Feature8 } from "@/components/features";
import { Footer1 } from "@/components/footer";
import { CTA2 } from "@/components/cta";
import { FAQ2 } from "@/components/faq";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header1 />
        <Hero4/>
        <Feature8/>
        <Testimonials1/>
        <CTA2/>
        <FAQ2/>
        <Footer1/>
      </body>
    </html>
  );
}
